name: Laravel

on:
  push:
  pull_request:

jobs:
  laravel-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - "7.3"
          - "7.4"
          - "8.0"
        experimental:
          - false

    name: PHP${{ matrix.php }} on ${{ matrix.os }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: jadual_test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, gd, fileinfo
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "locked"
          composer-options: "--prefer-dist --no-cache"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Sleep for 5 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Execute Feature Tests
        run: |
          php artisan migrate:refresh --seed --seeder="\Database\Seeders\TestDatabaseSeeder" --quiet
          php vendor/bin/phpunit -c phpunit.xml
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
          DB_DATABASE: jadual_test
          DB_CONNECTION: mysql

      - name: Upload Laravel Logs
        uses: actions/upload-artifact@v2-preview
        if: failure()
        with:
          name: logs
          path: storage/logs/laravel.log
